
name: Backup cuotas.csv desde memoria

on:
  schedule:
    - cron: '0 6,18 * * *'  # Dos veces al día
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Llamar a /recolectar
        run: |
          curl -s https://cuotas-recolector.onrender.com/recolectar
          echo "Esperando 10s para que Render procese..."
          sleep 10

      - name: Descargar CSV
        run: |
          curl -o cuotas.csv https://cuotas-recolector.onrender.com/descargar-csv
          if [ ! -s cuotas.csv ]; then
            echo "❌ Error: el archivo CSV está vacío"
            cat cuotas.csv
            exit 1
          fi

      - name: Crear carpeta y mover archivo
        run: |
          mkdir -p backups
          TS=$(date +'%Y-%m-%d_%H-%M')
          mv cuotas.csv "backups/cuotas_$TS.csv"

      - name: Commit y push si hubo cambios
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Actions Bot"

          git add backups/
          if git diff --cached --quiet; then
            echo "✅ Sin cambios, no se hace commit"
          else
            git commit -m "Backup automático del $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
